### ISSUE TITLE
WARN: Unresolved specs during Gem::Specification.reset:       http-cookie (~> 1.0) WARN: Clearing out unresolved specs.

### ISSUE THREAD

**Issue by NekomovYuyusuky** [flum1025/flumtter4#4]
flumtterをインストールして起動しようとしたところ次のようなエラーメッセージが表示され起動できませんでした。
当方初心者のため何か見落としがあるかもしれませんが報告させて頂きます。

環境
　　Ubuntu Gnome 16.04.3
　　http-cookie (1.0.3, 1.0.2)

エラーメッセージ
　　WARN: Unresolved specs during Gem::Specification.reset:
      http-cookie (~> 1.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/windows/tweet.rb:3:in `<module:Window>': uninitialized constant Flumtter::Window::Buf (NameError)
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/windows/tweet.rb:2:in `<module:Flumtter>'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/windows/tweet.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/core.rb:41:in `block in load_plugin'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/core.rb:39:in `each'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/core.rb:39:in `load_plugin'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/core.rb:46:in `sarastire'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/curses.rb:89:in `<module:Flumtter>'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/curses.rb:88:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/core.rb:41:in `block in load_plugin'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/core.rb:39:in `each'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/core.rb:39:in `load_plugin'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/core.rb:46:in `sarastire'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/core.rb:66:in `<module:Flumtter>'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/core/core.rb:5:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/main.rb:1:in `require_relative'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter/app/main.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/lib/flumtter.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/flumtter-5.9.1/exe/flumtter:5:in `<top (required)>'
	from /usr/local/bin/flumtter:23:in `load'
	from /usr/local/bin/flumtter:23:in `<main>'

**Comment by flum1025** [comment]
@NekomovYuyusuky ISSUEに気づくのが遅くなってしまい大変申し訳ありません。
たった今修正版あげましたのでもう一度`gem install flumtter`をしてお試しください。
よろしくお願いいたします。
