### ISSUE TITLE
First launch: uninitialized constant Flumtter::Window::Buf (NameError)

### ISSUE THREAD

**Issue by KenjiOhtsuka** [flum1025/flumtter4#6]
I got error.

```
% flumtter
Traceback (most recent call last):
	30: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	29: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	28: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/bin/flumtter:23:in `<main>'
	27: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/bin/flumtter:23:in `load'
	26: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/exe/flumtter:5:in `<top (required)>'
	25: from /Users/kenjiotsuka/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	24: from /Users/kenjiotsuka/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	23: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter.rb:2:in `<top (required)>'
	22: from /Users/kenjiotsuka/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	21: from /Users/kenjiotsuka/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	20: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/main.rb:1:in `<top (required)>'
	19: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/main.rb:1:in `require_relative'
	18: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/core.rb:5:in `<top (required)>'
	17: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/core.rb:66:in `<module:Flumtter>'
	16: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/core.rb:46:in `sarastire'
	15: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/core.rb:39:in `load_plugin'
	14: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/core.rb:39:in `each'
	13: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/core.rb:41:in `block in load_plugin'
	12: from /Users/kenjiotsuka/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	11: from /Users/kenjiotsuka/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	10: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/curses.rb:88:in `<top (required)>'
	 9: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/curses.rb:89:in `<module:Flumtter>'
	 8: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/core.rb:46:in `sarastire'
	 7: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/core.rb:39:in `load_plugin'
	 6: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/core.rb:39:in `each'
	 5: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/core.rb:41:in `block in load_plugin'
	 4: from /Users/kenjiotsuka/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /Users/kenjiotsuka/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 2: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/windows/mention.rb:1:in `<top (required)>'
	 1: from /Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/windows/mention.rb:2:in `<module:Flumtter>'
/Users/kenjiotsuka/.rvm/gems/ruby-2.5.1/gems/flumtter-5.9.2/lib/flumtter/app/core/windows/mention.rb:3:in `<module:Window>': uninitialized constant Flumtter::Window::Buf (NameError)
```

ruby version 2.5.1p57

**Comment by tomokazukozuma** [comment]
I have same error.

**Comment by haruby863** [comment]
同じエラーになりました。

## 動作環境
- OS
  - macOS Mojave 10.14.3
- brew
  - Homebrew 2.0.1
  - Homebrew/homebrew-core (git revision 3475e; last commit 2019-02-17)
- anyenv
  - rbenv: 2.5.1 (set by /Users/harumi.tahara/.anyenv/envs/rbenv/version)
- ruby
  - ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
- tmux
  - stable 2.8
- flumtter
  - flumtter (5.9.2)

## 再現手順
1. README.md に従って、インストール
  1. `$ gem install flumtter`
  1. `$ brew install ruby tmux`
  1. `$ flumtter`

## エラー内容

<details>

```console
$ flumtter
Traceback (most recent call last):
	26: from exe/flumtter:5:in `<main>'
	25: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	24: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	23: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter.rb:2:in `<top (required)>'
	22: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	21: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	20: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/main.rb:1:in `<top (required)>'
	19: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/main.rb:1:in `require_relative'
	18: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/core.rb:5:in `<top (required)>'
	17: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/core.rb:66:in `<module:Flumtter>'
	16: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/core.rb:46:in `sarastire'
	15: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/core.rb:39:in `load_plugin'
	14: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/core.rb:39:in `each'
	13: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/core.rb:41:in `block in load_plugin'
	12: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	11: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	10: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/curses.rb:88:in `<top (required)>'
	 9: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/curses.rb:89:in `<module:Flumtter>'
	 8: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/core.rb:46:in `sarastire'
	 7: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/core.rb:39:in `load_plugin'
	 6: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/core.rb:39:in `each'
	 5: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/core.rb:41:in `block in load_plugin'
	 4: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 2: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/windows/mention.rb:1:in `<top (required)>'
	 1: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/windows/mention.rb:2:in `<module:Flumtter>'
/Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/windows/mention.rb:3:in `<module:Window>': uninitialized constant Flumtter::Window::Buf (NameError)
```

</details>

## 回避方法
### 原因
```console
1: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/windows/mention.rb:2:in `<module:Flumtter>'
/Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/windows/mention.rb:3:in `<module:Window>': uninitialized constant Flumtter::Window::Buf (NameError)
```
https://github.com/flum1025/flumtter/blob/v5/lib/flumtter/app/core/windows/mention.rb

`require "flumtter/app/core/windows/buf_window"`を追記
```diff
diff --git a/lib/flumtter/app/core/windows/mention.rb b/lib/flumtter/app/core/windows/mention.rb
index 0f7d6e5..1914bcd 100644
--- a/lib/flumtter/app/core/windows/mention.rb
+++ b/lib/flumtter/app/core/windows/mention.rb
@@ -1,3 +1,5 @@
+require "flumtter/app/core/windows/buf_window"
+
 module Flumtter
   module Window
     class MentionBuf < Buf::Buf
```

APIキーの入力から、`Account Selector`まで進むのですが、
アカウントを選び、ツイート一覧の取得後、ストリーミング機能関係のエラーが出ます

## エラー内容
```console
19 ----------------------------------------------------------------------------------------------
hogehoge (@hogehoge)
hogehoge tweet
2019/02/18 14:46:33                                                          TwitPane for Android

hellnear96's stream_start!
#<Thread:0x00007ff89d9da2e0@/Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/client.rb:49 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	6: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/client.rb:53:in `block in stream'
	5: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/twitter-6.1.0/lib/twitter/streaming/client.rb:92:in `user'
	4: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/twitter-6.1.0/lib/twitter/streaming/client.rb:119:in `request'
	3: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/twitter-6.1.0/lib/twitter/streaming/connection.rb:22:in `stream'
	2: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/twitter-6.1.0/lib/twitter/streaming/response.rb:19:in `<<'
	1: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/twitter-6.1.0/lib/twitter/streaming/response.rb:19:in `<<'
/Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/twitter-6.1.0/lib/twitter/streaming/response.rb:24:in `on_headers_complete': Twitter::Error::NotFound
Traceback (most recent call last):
	5: from /Users/harumi.tahara/Desktop/oss_workspace/flumtter/lib/flumtter/app/core/client.rb:53:in `block in stream'
	4: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/twitter-6.1.0/lib/twitter/streaming/client.rb:92:in `user'
	3: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/twitter-6.1.0/lib/twitter/streaming/client.rb:119:in `request'
	2: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/twitter-6.1.0/lib/twitter/streaming/connection.rb:22:in `stream'
	1: from /Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/twitter-6.1.0/lib/twitter/streaming/response.rb:19:in `<<'
/Users/harumi.tahara/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/twitter-6.1.0/lib/twitter/streaming/response.rb:19:in `<<': Twitter::Error::NotFound
```

## 回避方法
`$ flumtter --non_stream`
ストリーミングAPIを使わなければ起動に成功します
